variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
variable "region" {}
variable "env_prefix" {}
variable "avail_zone" {}
variable "my_ip" {}
variable "public_key_path" {}
variable "private_key_path" {}
variable "instance_type" {}